#pragma once
#include "DX9_sound.h"
#define BGM_TITLE "title"
#define BGM_STAGE "stage"
#define BGM_ENDING "ending"
#define BGM_LASER "laser"
#define BGM_WIND "wind"

#define SE_MENU_CANCEL "cancel"
#define SE_MENU_DECIDE "decide"
#define SE_MENU_SELECT "cursor"
#define SE_PAUSE_OPEN "pause_open"
#define SE_PAUSE_CLOSE "pause_close"
#define SE_PUNCH "punch"
#define SE_FOOTSTEP "footstep"
#define SE_CLIMB "climb"
#define SE_JUMP "jump"
#define SE_WARNING "warning"

#define SE_HITARM "damaged"
#define SE_HITLASER "laserHit"
#define SE_BREAK "break"
#define SE_DUMMY "dummy"
#define SE_EXPLOSION "explosion"